{% set name = "dedupe-variable-datetime" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dedupe-variable-datetime-{{ version }}.tar.gz
  sha256: ce86100f11f5c9060ff0df5bd1ed56286f91836b7ba211e194b79889d41a403b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - datetime-distance
    - future
    - python >=3.6

test:
  imports:
    - dedupe.variables

about:
  home: https://github.com/datamade/dedupe-variable-datetime
  summary: DateTime variable type for dedupe
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - osamples
    - izahn
